## This file is automatically generated
## Standard maketest.g for the homalg project

LoadPackage( "Conley" );
LoadPackage( "GaussForHomalg" );
Read( "ListOfDocFiles.g" );
example_tree := ExtractExamples( DirectoriesPackageLibrary( "Conley", "doc" )[1]![1], "Conley.xml", list, 500 );
RunExamples( example_tree, rec( compareFunction := "uptowhitespace" ) );
GAPDocManualLab( "Conley" );
QUIT;
